function slides = generatePowerpointResults( imgsDir, pptFFN, widthHeightCellStr )
%GENERATEPOWERPOINTRESULTS Quick method for writing turker images to ppt.
%   slides = GENERATEPOWERPOINTRESULTS( imgsDir, pptFFN, widthHeightCellStr )
%   returns the powerpoint slides object given the inputted directory of
%   images generated by VISUALIZERESULTS. Each image is written to its own
%   blank slide on a powerpoint presentation document with a full file name
%   specified by pptFFN. The default width and height dimensions of the
%   images on every slide is specified by widthHeighCellStr.
%   
%   Note: widthHeightCellStr default is { '11.95 in', '7.25 in' }.
%   
%   See also: VISUALIZERESULTS.
%==========================================================================

narginchk( 3, 3 );
nargoutchk( 0, 1 );

% Write each image to a powerpoint slide.
d = dir( imgsDir );
ffns = fullfile( imgsDir, transpose( { d.name } ) );
ffns( 1:2 ) = []; % remove unix artifacts.
numImages = numel( ffns );
import mlreportgen.ppt.*
slides = Presentation( pptFFN );
for idx = 1:numImages
    picSlideIdx = add( slides, 'Blank' );
    plane = Picture( ffns{ idx } );
    plane.Width = widthHeightCellStr{ 1 };
    plane.Height = widthHeightCellStr{ 2 };
    add( picSlideIdx, plane );
end
% replace( slides, 'Content', plane )
close( slides );

